[project]
name = "world-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "tcod>=19.4.0",
]
