# Environmental System Configuration
# Controls how environmental factors (elevation, moisture, temperature) map to terrain types

[environmental_mapping]
# Terrain determination rules in priority order
# Each rule has conditions and the resulting terrain type

[[environmental_mapping.rules]]
name = "caves"
terrain_type = "caves"
conditions = { elevation_max = 0.2 }

[[environmental_mapping.rules]]
name = "deep_water"
terrain_type = "deep_water"
conditions = { elevation_max = 0.25 }

[[environmental_mapping.rules]]
name = "shallow_water"
terrain_type = "shallow_water"
conditions = { elevation_max = 0.35 }

[[environmental_mapping.rules]]
name = "swamp"
terrain_type = "swamp"
conditions = { elevation_max = 0.45, moisture_min = 0.75 }

[[environmental_mapping.rules]]
name = "desert"
terrain_type = "desert"
conditions = { temperature_min = 0.65, moisture_max = 0.35 }

[[environmental_mapping.rules]]
name = "fertile"
terrain_type = "fertile"
conditions = { moisture_min = 0.6, temperature_min = 0.4, temperature_max = 0.7, elevation_min = 0.35, elevation_max = 0.6 }

[[environmental_mapping.rules]]
name = "forest"
terrain_type = "forest"
conditions = { moisture_min = 0.6, temperature_min = 0.3, temperature_max = 0.8 }

[[environmental_mapping.rules]]
name = "mountains"
terrain_type = "mountains"
conditions = { elevation_min = 0.7, temperature_max = 0.4 }

[[environmental_mapping.rules]]
name = "hills"
terrain_type = "hills"
conditions = { elevation_min = 0.6 }

# Default terrain types based on moisture and temperature
[environmental_mapping.defaults]

[[environmental_mapping.defaults.rules]]
name = "grass_wet_hot"
terrain_type = "grass"
conditions = { moisture_min = 0.5, temperature_min = 0.6 }

[[environmental_mapping.defaults.rules]]
name = "dark_grass_wet_cold"
terrain_type = "dark_grass"
conditions = { moisture_min = 0.5, temperature_max = 0.4 }

[[environmental_mapping.defaults.rules]]
name = "light_grass_wet_medium"
terrain_type = "light_grass"
conditions = { moisture_min = 0.5 }

[[environmental_mapping.defaults.rules]]
name = "sand_dry_hot"
terrain_type = "sand"
conditions = { temperature_min = 0.6 }

[[environmental_mapping.defaults.rules]]
name = "dark_grass_dry_cold"
terrain_type = "dark_grass"
conditions = { temperature_max = 0.4 }

[[environmental_mapping.defaults.rules]]
name = "grass_default"
terrain_type = "grass"
conditions = {}

# Noise generation parameters
[noise]
elevation_octaves = 4
elevation_frequency = 0.01
elevation_amplitude = 1.0

moisture_octaves = 3
moisture_frequency = 0.008
moisture_amplitude = 0.8

temperature_octaves = 2
temperature_frequency = 0.005
temperature_amplitude = 0.6

# Temperature latitude influence
temperature_latitude_influence = 0.3
temperature_latitude_scale = 0.001
