# Visual Configuration for Tiles, Characters, and Colors
# Centralizes all visual representation data

# Terrain visual configurations
[terrain]

[terrain.deep_water]
characters = [" "]
foreground_color = [0, 0, 0]
background_color = [20, 50, 120]
passable = false
movement_cost = "inf"

[terrain.shallow_water]
characters = [" "]
foreground_color = [0, 0, 0]
background_color = [40, 80, 160]
passable = true
movement_cost = 2.0

[terrain.sand]
characters = [".", "·", "°"]
foreground_color = [194, 178, 128]
background_color = [238, 203, 173]
passable = true
movement_cost = 1.2

[terrain.grass]
characters = [".", ",", "'", "`"]
foreground_color = [34, 139, 34]
background_color = [0, 100, 0]
passable = true
movement_cost = 1.0

[terrain.light_grass]
characters = [".", ",", "'", "`"]
foreground_color = [144, 238, 144]
background_color = [50, 150, 50]
passable = true
movement_cost = 1.0

[terrain.dark_grass]
characters = [".", ",", "'", "`"]
foreground_color = [0, 100, 0]
background_color = [0, 50, 0]
passable = true
movement_cost = 1.0

[terrain.forest]
characters = ["♠", "♣", "T", "Y"]
foreground_color = [34, 139, 34]
background_color = [0, 50, 0]
passable = true
movement_cost = 1.5

[terrain.hills]
characters = ["^", "∩", "⩙"]
foreground_color = [139, 69, 19]
background_color = [160, 82, 45]
passable = true
movement_cost = 2.0

[terrain.mountains]
characters = ["▲", "⛰", "∆"]
foreground_color = [105, 105, 105]
background_color = [169, 169, 169]
passable = true
movement_cost = 3.0

[terrain.caves]
characters = [" "]
foreground_color = [0, 0, 0]
background_color = [25, 25, 25]
passable = true
movement_cost = 1.0

[terrain.desert]
characters = ["~", "≈", "∼"]
foreground_color = [255, 218, 185]
background_color = [238, 203, 173]
passable = true
movement_cost = 1.8

[terrain.swamp]
characters = ["≋", "~", "∿"]
foreground_color = [107, 142, 35]
background_color = [85, 107, 47]
passable = true
movement_cost = 2.5

[terrain.fertile]
characters = ["*", "✿", "❀"]
foreground_color = [50, 205, 50]
background_color = [34, 139, 34]
passable = true
movement_cost = 0.8

# Animal visual configurations
[animals]

[animals.sheep]
[animals.sheep.grazing]
characters = ["s"]
foreground_color = [255, 255, 255]

[animals.sheep.moving]
characters = ["S"]
foreground_color = [255, 255, 255]

[animals.sheep.fleeing]
characters = ["!"]
foreground_color = [255, 255, 255]

[animals.sheep.idle]
characters = ["s"]
foreground_color = [255, 255, 255]

[animals.cow]
[animals.cow.grazing]
characters = ["c"]
foreground_color = [0, 0, 0]

[animals.cow.moving]
characters = ["C"]
foreground_color = [0, 0, 0]

[animals.cow.fleeing]
characters = ["!"]
foreground_color = [0, 0, 0]

[animals.cow.idle]
characters = ["c"]
foreground_color = [0, 0, 0]

# UI element configurations
[ui]

[ui.cursor]
characters = ["X"]
foreground_color = [255, 255, 0]
background_color = [0, 0, 0]

[ui.crosshair]
characters = ["+"]
foreground_color = [255, 255, 0]

# Theme metadata
[theme]
name = "Default ASCII"
description = "Standard ASCII characters with color"
version = "1.0"
author = "Covenant Team"
